<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<Version>0.1.4</Version>
	<Product>PZDotNETCoreDiscordBot</Product>
  </PropertyGroup>

  <ItemGroup>
	<None Update="PZBot_Translations\*.json">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	</None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CoreRCON" Version="5.4.2" />
    <PackageReference Include="Discord.Net" Version="3.19.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.5" />
    <PackageReference Include="System.Management" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\" />
  </ItemGroup>

</Project>
